[tool.jupytext]
formats = "ipynb,scripts//py:percent"

[tool.ruff]
line-length = 120
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I001"
]
[tool.ruff.per-file-ignores]
"__init__.py" = ["E402", "F401", "F403"]
[tool.black]
line-length = 120
include = '\.pyi?$'
